#!/usr/bin/env python3
'''
Script to be used on the command line, it uses the first 
argument to search for modules on pypi websearch
Depends on BeautifulSoup4
'''

from re import findall, IGNORECASE
from requests import get
import sys

def help():
    print('''
    Usage:  pypi_search STRING
            pypi_search [OPTION]
    
    --help                      prints this help
    ''')


if __name__ == '__main__':

    # Exits if no argument was used
    if len(sys.argv) < 2:
        print('\nEmpty search string.\n')
        help()
        sys.exit(1)
    elif sys.argv[1] == '--help':
        help()
        sys.exit()

    URL = 'https://pypi.org/search/?q=' + sys.argv[1]
    RESULTS = get(URL)
    
    names = findall('<span class="package-snippet__name">*(.*)</span>',RESULTS.text,IGNORECASE)
    versions = findall('<span class="package-snippet__version">*(.*)</span>',RESULTS.text,IGNORECASE)
    descriptions = findall('<p class="package-snippet__description">*(.*)</p>',RESULTS.text,IGNORECASE)
    
    for i in range(5):
        print(names[i],versions[i])
        print('\t',descriptions[i],'\n')
